"""KarabinerPyX - A Python DSL for Karabiner-Elements Configuration."""

from karabinerpyx.deploy import (
    SaveResult,
    backup_config,
    reload_karabiner,
    save_config,
    save_config_path,
    validate_json,
)
from karabinerpyx.keys import (
    ALT,
    BS,
    CAPS,
    CMD,
    CTRL,
    DEL,
    DOWN,
    END,
    ENTER,
    ESC,
    HOME,
    L_ALT,
    L_CMD,
    L_CTRL,
    L_OPT,
    L_SHIFT,
    LEFT,
    OPT,
    PGDN,
    PGUP,
    R_ALT,
    R_CMD,
    R_CTRL,
    R_OPT,
    R_SHIFT,
    RET,
    RIGHT,
    SHIFT,
    SPC,
    TAB,
    UP,
)
from karabinerpyx.layer import LayerStackBuilder, SimultaneousManipulator
from karabinerpyx.models import (
    KarabinerConfig,
    Manipulator,
    Profile,
    RawManipulator,
    Rule,
)
from karabinerpyx.templates import MACRO_TEMPLATES, make_shell_command

__version__ = "0.2.0"

__all__ = [
    "KarabinerConfig",
    "Manipulator",
    "RawManipulator",
    "Profile",
    "Rule",
    "LayerStackBuilder",
    "SimultaneousManipulator",
    "MACRO_TEMPLATES",
    "make_shell_command",
    "SaveResult",
    "backup_config",
    "reload_karabiner",
    "save_config",
    "save_config_path",
    "validate_json",
    "CMD",
    "ALT",
    "OPT",
    "CTRL",
    "SHIFT",
    "R_CMD",
    "L_CMD",
    "R_ALT",
    "L_ALT",
    "R_OPT",
    "L_OPT",
    "R_CTRL",
    "L_CTRL",
    "R_SHIFT",
    "L_SHIFT",
    "CAPS",
    "ESC",
    "RET",
    "ENTER",
    "SPC",
    "TAB",
    "BS",
    "DEL",
    "UP",
    "DOWN",
    "LEFT",
    "RIGHT",
    "PGUP",
    "PGDN",
    "HOME",
    "END",
]
